### ISSUE TITLE
ImGui::ImageButton(const sf::Sprite& sprite) ignores rotation

### ISSUE THREAD

**Issue by Boronak** [SFML/imgui-sfml#86]
ImGui::ImageButton(const sf::Sprite& sprite) takes the texture and position but ignores the rotation of the sprite.

**Comment by eliasdaler** [comment]
Indeed, right now `sf::Sprite`'s transform is ignored, but I can only make it work with `ImGui::Image`, because there's no way to draw rotated image using `ImGui::ImageButton`.

I think what you need to do is to make custom ImageButton, which will copy how [original ImageButton is implemented](https://github.com/ocornut/imgui/blob/cb7ba60d3f7d691c698c4a7499ed64757664d7b8/imgui_widgets.cpp#L932), but instead use advice from [this issue](https://github.com/ocornut/imgui/issues/1982) and use `AddImageQuad` instead of `AddImage`.

Sorry, I don't want to implement this custom ImageButton in ImGui-SFML, because it will mean that I'll need to access ImGui's private API which will make things a lot more difficult.

But I'll eventually support `sf::Sprite`'s transform in `ImGui::Image`

**Comment by eliasdaler** [comment]
Another workaround (which is a lot easier!) is to draw sprite onto `sf::RenderTexture` and then pass it into `ImageButton` overload for `sf::Texture`. You're likely to encounter #35 then, and if you do - I'll add `Image`/`ImageButton` overload for `sf::RenderTexture` ASAP.

**Comment by Boronak** [comment]
I am now using the workaround of drawing the rotated sprite to a `RenderTexture` and flipping it to counteract #35.

**Comment by eliasdaler** [comment]
Okay, I'll add overload for `sf::RenderTexture` soon

**Comment by oprypin** [comment]
Could you please actually add that overload? :s

**Comment by eliasdaler** [comment]
"Soon" was 1.5 years ago... Shame on me.
Okay, I'll try to add it this week. But if someone provides a PR it would get into master even quicker. ;)

**Comment by eliasdaler** [comment]
Update: fix for RenderTexture is not in master and released in v2.2

If I manage to do #87, the sprite transform might be taken into account. I'll see what i can do.
